config/routes.rb
#map.namespace :admin do |admin|
#  admin.resources :comments
#  admin.resources :comment_types
#
#  admin.resources :orders, :member => {:comments => :get} do |order|
#    order.resources :shipments, :member => {:comments => :get}
#  end
#end
#

Rails.application.routes.draw do
  namespace :admin do
    resources :comments
    resources :comment_types

    resources :orders do
      member do
        get :comments
      end

      resources :shipments do
        member do
         get :comments
       end
      end
    end
  end

#match '/admin/comments' => 'admin/comments', :via => [:get, :post]
#  match '/admin/comment_types' => 'admin/comment_types', :via => [:get, :post]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  belongs_to :comment_type

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

end

app/models/comment_type.rb
class CommentType < ActiveRecord::Base
  has_many :comments
end

app/controllers/admin/comment_types_controller.rb
class Admin::CommentTypesController < Admin::BaseController
  resource_controller

  update.wants.html { redirect_to collection_url }
  create.wants.html { redirect_to collection_url }
  destroy.success.wants.js { render_js_for_destroy }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  resource_controller

  create.response do |wants|
    # go to edit form after creating as new product
    wants.html {redirect_to :back}
  end

end

app/views/admin/comment_types/_form.html.erb
<%- locals = {:f => f} -%>
<%= hook :admin_comment_type_form_fields, locals do %>
  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %><br />
    <%= f.text_field :name, :class => 'fullwidth title' %>
    <%= error_message_on :comment_type, :name %>
  <% end %>

  <%= f.field_container :applies_to do %>
    <%= f.label :applies_to, t("applies_to") %><br />
    <%= f.text_field :applies_to, :value => f.object.nil? ? "Order" : f.object.applies_to, :class => 'fullwidth title' %>
    <%= error_message_on :comment_type, :applies_to%>
  <% end %>

<% end %>

app/views/admin/comment_types/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<%= hook :admin_comment_type_edit_form_header do %>
  <h1><%= t("editing_comment_type") %></h1>
  <%= render "shared/error_messages", :target => @comment_type %>
<% end %>

<%= hook :admin_comment_type_edit_form do %>
  <%= form_for(@comment_type, :url => object_url, :html => { :method => :put }) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>

    <%= hook :admin_comment_type_edit_form_buttons do %>
      <%= render :partial => "admin/shared/edit_resource_links" %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/comment_types/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_comment_type"), new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("comment_types") %></h1>

<table class="index">
  <thead>
    <tr>
    <%= hook :admin_comment_types_index_headers do %>
      <th><%= t("name") %></th>
      <th><%= t("applies_to") %></th>
    <% end %>
      <th>
        <% hook :admin_comment_types_index_header_actions %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @comment_types.each do |comment_type| %>
      <tr id="<%= dom_id comment_type %>">
        <%- locals = {:comment_type => comment_type} -%>
        <%= hook :admin_comment_types_index_rows, locals do %>
          <td><%= comment_type.name %></td>
          <td><%= comment_type.applies_to %></td>
        <% end %>
        <td width="140px">
          <%= hook :admin_comment_types_index_row_actions, locals do %>
            <%= link_to_edit comment_type %> &nbsp;
            <%= link_to_delete comment_type %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/comment_types/new.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<%= hook :admin_comment_type_new_form_header do %>
  <h1><%= t("new_comment_type") %></h1>

  <%= render "shared/error_messages", :target => @comment_type %>
<% end %>

<%= hook :admin_comment_type_new_form do %>
  <%= form_for(:comment_type, :url => collection_url) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>

    <%= hook :admin_comment_type_new_form_buttons do %>
      <%= render :partial => "admin/shared/new_resource_links" %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/orders/_tab.html.erb
<li <%= raw ' class="active"' if (defined? current and current == "Comments") %>>
  <%= link_to t("comments"), comments_admin_order_url(@order) %>
</li>

app/views/admin/orders/comments.html.erb
<%= render "admin/shared/order_tabs", :current => "Comments" %>
<%= render "admin/shared/comments", :commentable => @order %>

app/views/admin/shared/_comment_list.html.erb
<table class="index">
  <tr>
    <th style="width:140px;"><%= "#{I18n::t('spree.date')}/#{I18n::t('spree.time')}" %></th>
    <% if @comment_types and !@comment_types.empty? %>
      <th><%= I18n::t("type") %></th>
    <% end %>
    <th><%= I18n::t("comment") %></th>
  </tr>
  <% commentable.comments.reverse.each_with_index do |comment, index| %>
    <tr id="<%= dom_id(comment) %>">
      <td><%= comment.created_at.to_formatted_s(:long) %></td>
      <% if @comment_types and !@comment_types.empty? %>
        <td><%= comment.comment_type.name if comment.comment_type %></td>
      <% end %>
      <td>
        <div id="order-comment-header-<%= index %>" class="order-comment-header">
          <strong><%= comment.user.email + ' ' + I18n::t('said')%> :</strong>
        </div>
        <div id="order-comment-body-<%= index %>" class="order-comment-body">
          <%= comment.comment.html_safe %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/shared/_comments.html.erb
<h1><%= "#{t("comments")} #{(t('for') + " " + comments_for unless (comments_for rescue nil).nil?)}"%></h1>

<%= render 'admin/shared/comment_list', :commentable => commentable %>

<div class="order-add-comment">
  <% form_for(:comment, :url => admin_comments_url) do |f| %>
    <%= hidden_field_tag 'comment[commentable_id]', commentable.id %>
    <%= hidden_field_tag 'comment[commentable_type]', commentable.class %>
    <%= hidden_field_tag 'comment[user_id]', current_user.id %>

    <table class="index">
      <thead>
        <th colspan="2"><%= t('add_comment') %></th>
      </thead>
      <tbody>
        <% if @comment_types and !@comment_types.empty? %>
          <tr>
            <td><%= f.label :comment_type_id, t("type") %><br /></td>
            <td><%= f.select :comment_type_id, @comment_types.map{|ct| [ct.name, ct.id]},{} ,:class => 'title' %></td>
          </tr>
        <% end %>
        <tr>
          <td style="width:140px;"><%= f.label :comment, t("comment") %></td>
          <td><%= f.text_area :comment,  {:style => 'height:150px;', :class => 'fullwidth'} %></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>      <%= button t('add_comment') %></td>
        </tr>
      </tbody>
    </table>

    <p class="form-buttons">

    </p>
  <% end %>
</div>

app/views/admin/shipments/_button.html.erb
<li>
  <%= button_link_to(t("comments"), comments_admin_order_shipment_url(@order, @shipment)) %>
</li>

app/views/admin/shipments/comments.html.erb
<%= render "admin/shared/order_tabs", :current => "Shipments" %>
<%= render "admin/shared/comments", {:commentable => @shipment, :comments_for => "Shipment ##{@shipment.number}"} %>